config/routes.rb
Rails.application.routes.draw do
  resources :nominees
  resources :awards
  resources :electoral_citizens
  resources :registry_citizens
  resources :nhis_citizens
  resources :dvla_citizens
  resources :all_citizens
  get 'static_pages/about'
  get 'all_citizens/info'
  devise_for :users
  root "all_citizens#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
  has_many :nominees, dependent: :destroy
  validates_presence_of :name, :description
end

app/models/dvla_citizen.rb
class DvlaCitizen < ApplicationRecord
  connects_to database: { writing: :DVLA, reading: :DVLA }
end

app/models/electoral_citizen.rb
class ElectoralCitizen < ApplicationRecord
end

app/models/nhis_citizen.rb
class NhisCitizen < ApplicationRecord
  connects_to database: { writing: :NHIS, reading: :NHIS }
end

app/models/nominee.rb
class Nominee < ApplicationRecord
  belongs_to :award

  validates_presence_of :first_name, :last_name, :biography
end

app/models/registry_citizen.rb
class RegistryCitizen < ApplicationRecord
  connects_to database: { writing: :Birthdeathregistry, reading: :Birthdeathregistry }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/all_citizens_controller.rb
class AllCitizensController < ApplicationController
  before_action :authenticate_user!

  def index
    @registry_citizens = RegistryCitizen.all
    @electoral_citizens = ElectoralCitizen.all
    @nhis_citizens = NhisCitizen.all
    @dvla_citizens = DvlaCitizen.all
  end

  def create
    key = all_citizen_params["key"].strip
    search = all_citizen_params["gender"]

    ActiveRecord::Base.connected_to(role: :reading) do
      # all code in this block will be connected to the reading role
    end

    if search == "1"
      @result = [RegistryCitizen, ElectoralCitizen, NhisCitizen, DvlaCitizen].map do |model|
        model.where('last_name LIKE ?', key)
      end
    elsif search == "2"
      @result = [RegistryCitizen, ElectoralCitizen, NhisCitizen, DvlaCitizen].map do |model|
        model.where('general_id LIKE ?', key.to_i)
      end
    else
      @result = [RegistryCitizen, ElectoralCitizen, NhisCitizen, DvlaCitizen].map do |model|
        model.where('first_name LIKE ?', key)
      end
    end

    session[:result] = @result

    # @registry_citizens = []
    # @electoral_citizens = []
    # @nhis_citizens = []
    # @dvla_citizens = []

    redirect_to all_citizens_info_path
  end

  def info; end

  def show; end

  private

  def all_citizen_params
    params.permit(:key, :gender, :authenticity_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :authenticate_user!
  def index
    @awards = Award.all
  end

  def new
    @award = Award.new
  end

  def show
    @award = Award.find_by(id: params[:id])
  end

  def create
    @award = Award.new(awards_params)

    if @award.save
      flash[:notice] = "Created an Award"
      redirect_to @award
    else
      render :new
    end
  end

  private
  def awards_params
    params.require(:award).permit(:name, :description, :image)
  end

end

app/controllers/dvla_citizens_controller.rb
class DvlaCitizensController < ApplicationController
  before_action :authenticate_user!
  def index
    @dvla_citizens = DvlaCitizen.all
  end

  def show
    @dvla_citizen = DvlaCitizen.find(params[:id])
  end

  def new
    @dvla_citizen = DvlaCitizen.new
    # @awards = Award.all
  end

  def create
    filename = "#{Time.now.to_i}#{File.extname(dvla_citizen_params[:image].tempfile)}"
    @dvla_citizen = DvlaCitizen.new(dvla_citizen_params.except(:image))
    @dvla_citizen.image = filename

    if @dvla_citizen.save
      flash[:notice] = 'DVLA Record Created!'
      file = dvla_citizen_params[:image].tempfile
      destination = "#{Rails.root}/app/assets/images/#{@dvla_citizen.image}"
      File.copy_stream(file, destination)
      redirect_to @dvla_citizen
    else
      render :new
    end
  end

  private

  def dvla_citizen_params
    params.require(:dvla_citizen).permit(:first_name, :last_name, :general_id, :description, :image)
  end
end

app/controllers/electoral_citizens_controller.rb
class ElectoralCitizensController < ApplicationController
  before_action :authenticate_user!
  def index
    @electoral_citizens = ElectoralCitizen.all
  end

  def show
    @electoral_citizen = ElectoralCitizen.find(params[:id])
  end

  def new
    @electoral_citizen = ElectoralCitizen.new
    # @awards = Award.all
  end

  def create
    filename = "#{Time.now.to_i}#{File.extname(electoral_citizen_params[:image].tempfile)}"
    @electoral_citizen = ElectoralCitizen.new(electoral_citizen_params.except(:image))
    @electoral_citizen.image = filename

    if @electoral_citizen.save
      flash[:notice] = 'Electoral Commission Record Created!'
      file = electoral_citizen_params[:image].tempfile
      destination = "#{Rails.root}/app/assets/images/#{@electoral_citizen.image}"
      File.copy_stream(file, destination)
      redirect_to @electoral_citizen
    else
      render :new
    end
  end

  private

  def electoral_citizen_params
    params.require(:electoral_citizen).permit(:first_name, :last_name, :general_id, :description, :image)
  end
end

app/controllers/nhis_citizens_controller.rb
class NhisCitizensController < ApplicationController
  before_action :authenticate_user!
  def index
    @nhis_citizens = NhisCitizen.all
  end

  def show
    @nhis_citizen = NhisCitizen.find(params[:id])
  end

  def new
    @nhis_citizen = NhisCitizen.new
    # @awards = Award.all
  end

  def create
    filename = "#{Time.now.to_i}#{File.extname(nhis_citizen_params[:image].tempfile)}"
    @nhis_citizen = NhisCitizen.new(nhis_citizen_params.except(:image))
    @nhis_citizen.image = filename

    if @nhis_citizen.save
      flash[:notice] = 'NHIS Record Created!'
      file = nhis_citizen_params[:image].tempfile
      destination = "#{Rails.root}/app/assets/images/#{@nhis_citizen.image}"
      File.copy_stream(file, destination)
      redirect_to @nhis_citizen
    else
      render :new
    end
  end

  private

  def nhis_citizen_params
    params.require(:nhis_citizen).permit(:first_name, :last_name, :general_id, :description, :image)
  end
end

app/controllers/nominees_controller.rb
class NomineesController < ApplicationController
  before_action :authenticate_user!
  def index
    @nominees =Nominee.all
  end

  def show
    @nominee = Nominee.find(params[:id])
  end

  def new
    @nominee = Nominee.new
    @awards = Award.all
  end

  def create
    @nominee = Nominee.new(nominees_params)
    @nominee.award_id = params[:award]

    if @nominee.save
      flash[:notice] = "Created an Award"
      redirect_to @nominee
    else
      render :new
    end
  end

  private
  def nominees_params
    params.require(:nominee).permit(:first_name, :last_name, :biography, :video, :image)
  end
end

app/controllers/registry_citizens_controller.rb
class RegistryCitizensController < ApplicationController
  before_action :authenticate_user!
  def index
    @registry_citizens =RegistryCitizen.all
  end

  def show
    @registry_citizen = RegistryCitizen.find(params[:id])
  end

  def new
    @registry_citizen = RegistryCitizen.new
    # @awards = Award.all
  end

  def create
    filename = "#{Time.now.to_i}#{File.extname(registry_citizen_params[:image].tempfile)}"
    @registry_citizen = RegistryCitizen.new(registry_citizen_params.except(:image))
    @registry_citizen.image = filename

    if @registry_citizen.save
      flash[:notice] = 'Birth And Death Registry Record Created!'
      file = registry_citizen_params[:image].tempfile
      destination = "#{Rails.root}/app/assets/images/#{@registry_citizen.image}"
      File.copy_stream(file, destination)
      redirect_to @registry_citizen
    else
      render :new
    end
  end

  private
  def registry_citizen_params
    params.require(:registry_citizen).permit(:first_name, :last_name, :general_id, :description, :image)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/all_citizens/index.html.erb
<div class="ui center aligned container" >
  <div class="ui mini segment" >
    <span class="ui huge header">CATEGORIES</span>
  </div>
  <div class="ui container">
    <div class="ui segments">
      <div class="ui purple segment">
        <%= form_with(class: "ui form") do |f| %>
          
          <div class="field">
            <h2 class="ui header">Search</h2>
          </div>
          <div class="field">
            <%= f.text_field :key, required: true, placeholder: "Search Keyword" %>
          </div>
          <div class="field">
            <div class="ui selection dropdown">
              <input type="hidden" name="gender">
              <i class="dropdown icon"></i>
              <div class="default text">Search By</div>
              <div class="menu">

                  <div class="item" data-value="0">First Name</div>
                  <div class="item" data-value="1">Last Name</div>
                  <div class="item" data-value="2">General ID</div>
              </div>
          </div>
          </div>
          <input class="ui huge purple submit button" type="submit">
        <% end %>

      </div>
      <div class="ui red inverted segment">
        

        <div class="ui header">ELECTORAL COMMISSION</div>
          <div class="ui link centered cards">
          <%@electoral_citizens.each do |citizen|%>
           <%= link_to electoral_citizen_path(citizen) do %>
              <div class="ui card">
                <div class="image">
                  <%= image_tag(citizen.image, class: "ui rounded image") %>
                </div>
                  <%= link_to "#{citizen.first_name}", electoral_citizen_path(citizen), class: "ui basic huge bottom attached label"%>
              </div>
            <% end %>
          <% end %>
          </div>
        </div>
      </div>
      <div class="ui yellow inverted segment">

        <div class="ui header">BIRTH AND DEATH REGISTRY</div>
          <div class="ui link centered cards">
          <%@registry_citizens.each do |citizen|%>
           <%= link_to registry_citizen_path(citizen) do %>
              <div class="ui card">
                <div class="image">
                  <%= image_tag(citizen.image, class: "ui rounded image") %>
                </div>
                  <%= link_to "#{citizen.first_name}", registry_citizen_path(citizen), class: "ui basic huge bottom attached label"%>
              </div>
            <% end %>
          <% end %>
          </div>
        </div>
      </div>
      <div class="ui green inverted segment">

        <div class="ui header">NHIS</div>
          <div class="ui link centered cards">
          <%@nhis_citizens.each do |citizen|%>
           <%= link_to nhis_citizen_path(citizen) do %>
              <div class="ui card">
                <div class="image">
                  <%= image_tag(citizen.image, class: "ui rounded image") %>
                </div>
                  <%= link_to "#{citizen.first_name}", nhis_citizen_path(citizen), class: "ui basic huge bottom attached label"%>
              </div>
            <% end %>
          <% end %>
          </div>
        </div>
        <div class="ui blue inverted segment">
  
          <div class="ui header">DVLA</div>
            <div class="ui link centered cards">
            <%@dvla_citizens.each do |citizen|%>
             <%= link_to dvla_citizen_path(citizen) do %>
                <div class="ui card">
                  <div class="image">
                    <%= image_tag(citizen.image, class: "ui rounded image") %>
                  </div>
                    <%= link_to "#{citizen.first_name}", nhis_citizen_path(citizen), class: "ui basic huge bottom attached label"%>
                </div>
              <% end %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('select.dropdown').dropdown();
</script>

app/views/all_citizens/show.html.erb
<div class="ui center aligned container" >
  <div class="ui mini segment" >
    <span class="ui huge header">RESULT</span>
  </div>
  <div class="ui container">
    <div class="ui segments">
      <div class="ui red inverted segment">
        

        <!-- <div class="ui header">RESULT</div> -->
          <div class="ui link centered cards">
          <%session[:result].each_with_index do |result, index|%>
          <%result.each do |citizen|%>
          <div class="ui red inverted segment">
        

              <div class="ui link centered cards">
                <% path = registry_citizen_path(citizen["id"]) if index == 0 %>
                <% path = electoral_citizen_path(citizen["id"]) if index == 1 %>
                <% path = nhis_citizen_path(citizen["id"]) if index == 2 %>
                <% path = dvla_citizen_path(citizen["id"]) if index == 3 %>
               <%= link_to path do %>
                  <div class="ui card">
                    <div class="image">
                      <%= image_tag(citizen["image"], class: "ui rounded image") %>
                    </div>
                      <%= link_to "#{citizen["first_name"]}", path, class: "ui basic huge bottom attached label"%>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <% end %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('select.dropdown').dropdown();
</script>

app/views/awards/_form.html.erb
<div class="ui center aligned container" style="width:60%">
  <div class="ui container">
    <div class="ui segment">
    <%= form_for @award, html: {class: "ui form"}, method: :post, class: "ui form",  multipart: true do |f| %>
  <ul>
  <% @award.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <div class="field" style="font-size: 1.3em;">
    <%= f.label :name%><br />
    <%= f.text_field :name, required: true, placeholder: "Input a descriptive title" %>
  </div>

  <div class="field" style="font-size: 1.3em;">
    <%= f.label :description%><br />
    <%= f.text_area :description, required: true, placeholder: "Add a good description" %>
  </div>
  <div class="field">
    <%= f.file_field "image", required: true, class: "ui button", accept: "image/*"%>
  </div>
  <p>
    <%= f.submit "Create Article", class: "ui primary button", style: "font-size: 1.2em;"%>
  </p>
  
<% end %>
</div>

</div>
</div>

app/views/awards/index.html.erb
<div class="ui center aligned container" >
  <div class="ui huge segment" >
    <%= link_to "Create new award", new_award_path, class: "floating ui purple tag label"%>
    <span class="ui huge header">CATEGORIES</span>
  </div>
  <div class="ui container">
    <div class="ui segment">
        <div class="ui link centered cards">
          <%@awards.each do |award|%>
           <%= link_to award_path(award) do %>
              <div class="ui card">
                <div class="image">
                  <%= image_tag("lolx.jfif", class: "ui rounded image") %>
                </div>
                  <%= link_to "#{award.name}", award_path(award), class: "ui basic huge bottom attached label"%>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/awards/new.html.erb
<div class="ui center aligned container" >
  <div class="ui huge segment">
    <h2 class="ui huge header">ADD CATEGORY</h2>
  </div>
  <%= render partial: 'form'%>
</div>

app/views/awards/show.html.erb
<div id="content">
  <div class="ui container">
    <div class="ui center aligned segment">
      <h2 class="huge header"><%= @award.name.upcase %></h2>
    </div>
    <div class="ui placeholder stacked segment">
      <div class="ui two column stackable center aligned grid">
        <div class="ui vertical divider"><i class="massive trophy icon"></i></div>
        <div class="middle aligned row">
          <div class="column">
            <div class="ui medium image">
                <%= image_tag("lolx.jfif", class: "ui image") %>
            </div>
          </div>
          <div class="column">
            <h2>Description</h2>
            <div class="ui icon header">
              <%= @award.description.upcase %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="ui center aligned container" style="width: 60%;">
      <div class="ui segment">
        <h3>Nominees</h3>
      </div>
      <div class="ui small sequenced images">
        <% @award.nominees.each do |nominee|%>
          <%= link_to nominee_path(nominee) do%>
          <%= image_tag("lolx.jfif", class: "ui circular image ") %>
          <% end %>
        <% end %>
      </div>
    </div>
    
  </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
<script>
  
  $('.sequenced.images .image').hover().transition({
    debug     : true,
        animation : 'jiggle',
        duration  : 500,
        interval  : 200
  });

</script>

app/views/dvla_citizens/_form.html.erb
<div class="ui center aligned container" style="width:60%">
  <div class="ui container">
    <div class="ui segment">
    <%= form_for @dvla_citizen, html: {class: "ui form"}, method: :post, class: "ui form",  multipart: true do |f| %>
  <ul>
  <% @dvla_citizen.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <div class="field" style="font-size: 1.3em;">
    <%= f.label :first_name%><br />
    <%= f.text_field :first_name, required: true, placeholder: "First Name", autofocus: true %>
  </div>
  <div class="field" style="font-size: 1.3em;">
    <%= f.label :last_name%><br />
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>

  <div class="field" style="font-size: 1.3em;">
    <%= f.label "General ID" %><br />
    <%= f.text_field :general_id, required: true, placeholder: "Add a general ID" %>
  </div>
  <div class="field" style="font-size: 1.3em;">
    <%= f.label :description%><br />
    <%= f.text_area :description, required: true, placeholder: "Add a Description" %>
  </div>
  <div class="field">
    <%= f.file_field "image", class: "ui button", accept: "image/*"%>
  </div>
  <p>
    <%= f.submit "Submit", class: "ui primary button", style: "font-size: 1.2em;"%>
  </p>
  
<% end %>
</div>

</div>
</div>

app/views/dvla_citizens/index.html.erb
<div class="ui center aligned container" >
  <div class="ui huge blue inverted segment" ">
    <%= link_to "Create new DVLA Citizen", new_dvla_citizen_path, class: "floating ui black tag label"%>
    <span class="ui huge header">DVLA</span>
  </div>
  <div class="ui center aligned container" style="width: 50%">
    <%@dvla_citizens.each do |citizen|%>
      <div class="ui segment">
        <div class="ui vertical divider"><i class="info icon"></i></div>
        <div class="ui two column grid">
          <%= link_to dvla_citizen_path(citizen), class: "column" do %>
            <div class="ui small stretched image">
              <%= image_tag(citizen.image, class: "ui rounded image") %>
            </div>
          <% end %>
          <%= link_to dvla_citizen_path(citizen), class: "column" do %>
          <div class="column" style="color: black;">
            <h2 class="header"><%= "#{citizen.first_name.upcase} #{citizen.last_name.upcase}"%></h2>
            <h5 class="header" style="text-decoration: underline; font-weight:lighter">General ID</h5>
            <h3 class="header"><%= citizen.general_id%></h3>
            <h5 class="header" style="text-decoration: underline; font-weight:lighter">Description</h5>
            <h3 class="header"><%= citizen.description%></h3>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dvla_citizens/new.html.erb
<div class="ui center aligned container" >
  <div class="ui huge segment">
    <h2 class="ui huge header">ADD CITIZEN TO DVLA</h2>
  </div>
  <%= render partial: 'form'%>
</div>

app/views/electoral_citizens/index.html.erb
<div class="ui center aligned container" >
  <div class="ui huge red inverted segment" >
    <%= link_to "Create new Electoral Commission Record", new_electoral_citizen_path, class: "floating ui black tag label"%>
    <span class="ui huge header">ELECTORAL COMMISSION</span>
  </div>
  <div class="ui center aligned container" style="width: 50%">
    <%@electoral_citizens.each do |citizen|%>
      <div class="ui segment">
        <div class="ui vertical divider"><i class="info icon"></i></div>
        <div class="ui two column grid">
          <%= link_to nhis_citizen_path(citizen), class: "column" do %>
            <div class="ui small stretched image">
              <%= image_tag(citizen.image, class: "ui rounded image") %>
            </div>
          <% end %>
          <%= link_to nhis_citizen_path(citizen), class: "column" do %>
          <div class="column" style="color: black;">
            <h2 class="header"><%= "#{citizen.first_name.upcase} #{citizen.last_name.upcase}"%></h2>
            <h5 class="header" style="text-decoration: underline; font-weight:lighter">General ID</h5>
            <h3 class="header"><%= citizen.general_id%></h3>
            <h5 class="header" style="text-decoration: underline; font-weight:lighter">Description</h5>
            <h3 class="header"><%= citizen.description%></h3>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/electoral_citizens/new.html.erb
<div class="ui center aligned container" >
  <div class="ui huge segment">
    <h2 class="ui huge header">ADD RECORD TO ELECTORAL COMMISION</h2>
  </div>
  <%= render partial: 'form'%>
</div>

app/views/nhis_citizens/index.html.erb
<div class="ui center aligned container" >
  <div class="ui huge green inverted segment" >
    <%= link_to "Create new nhis Citizen", new_nhis_citizen_path, class: "floating ui black tag label"%>
    <span class="ui huge header">NHIS</span>
  </div>
  <div class="ui center aligned container" style="width: 50%">
    <%@nhis_citizens.each do |citizen|%>
      <div class="ui segment">
        <div class="ui vertical divider"><i class="info icon"></i></div>
        <div class="ui two column grid">
          <%= link_to nhis_citizen_path(citizen), class: "column" do %>
            <div class="ui small stretched image">
              <%= image_tag(citizen.image, class: "ui rounded image") %>
            </div>
          <% end %>
          <%= link_to nhis_citizen_path(citizen), class: "column" do %>
          <div class="column" style="color: black;">
            <h2 class="header"><%= "#{citizen.first_name.upcase} #{citizen.last_name.upcase}"%></h2>
            <h5 class="header" style="text-decoration: underline; font-weight:lighter">General ID</h5>
            <h3 class="header"><%= citizen.general_id%></h3>
            <h5 class="header" style="text-decoration: underline; font-weight:lighter">Description</h5>
            <h3 class="header"><%= citizen.description%></h3>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/nhis_citizens/new.html.erb
<div class="ui center aligned container" >
  <div class="ui huge segment">
    <h2 class="ui huge header">ADD CITIZEN TO NHIS</h2>
  </div>
  <%= render partial: 'form'%>
</div>

app/views/nominees/index.html.erb
<div class="ui center aligned container" >
  <div class="ui huge segment" style="background-image: linear-gradient(to right, rgb(128, 88, 15), rgb(107, 107, 184), rgb(108, 202, 108));">
    <%= link_to "Create new Nominee", new_nominee_path, class: "floating ui purple tag label"%>
    <span class="ui huge header">NOMINEES</span>
  </div>
  <div class="ui center aligned container" style="width: 50%">
    <%@nominees.each do |nominee|%>
      <div class="ui segment">
        <div class="ui vertical divider"><i class="info icon"></i></div>
        <div class="ui two column grid">
          <%= link_to nominee_path(nominee), class: "column" do %>
            <div class="ui small stretched image">
              <%= image_tag("lolx.jfif", class: "ui rounded image") %>
            </div>
          <% end %>
          <%= link_to nominee_path(nominee), class: "column" do %>
          <div class="column" style="color: black;">
            <h2 class="header"><%= "#{nominee.first_name.upcase} #{nominee.last_name.upcase}"%></h2>
            <h5 class="header" style="text-decoration: underline; font-weight:lighter">category</h5>
            <h3 class="header"><%= nominee.award.name.upcase%></h3>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/nominees/new.html.erb
<div class="ui center aligned container" >
  <div class="ui huge segment">
    <h2 class="ui huge header">ADD NOMINEE</h2>
  </div>
  <%= render partial: 'form'%>
</div>

app/views/nominees/show.html.erb
<div id="content">
  <div class="ui container">
    <div class="ui center aligned segment">
      <h2 class="huge inverted header">Nominated for the
        <span >
          <%= link_to @nominee.award.name.upcase, award_path(@nominee.award)%>
        </span>
        award</h2>
    </div>
    <div class="ui center aligned container">
      <div class="ui three column stackable center aligned grid">
        <div class="column">
          <div class="ui segment">
              <h4 class="header" style="text-decoration: underline;">name</h4>
              <h1><%= @nominee.first_name%> <%= @nominee.last_name%></h1>
          </div>
        </div>
        <div class="column">
          <div class="ui segment">
              <div class="ui slide masked reveal">
                <%= image_tag("lolx.jfif", class: "visible content")%>
                <%= image_tag("lolx.jfif", class: "hidden content")%>
              </div>
          </div>
        </div>
        <div class="column">
          <div class="ui segment">
            <h4 class="header" style="text-decoration: underline;">Biography</h4>
          <h1>
            <%= @nominee.biography%>
          </h1>
          </div>
        </div>
      </div>
      <!-- <div class="ui center aligned placeholder piled segment">
        <div class="ui left dividing rail">
          <h1 class="ui container" style="background-color: red; margin-top: 50%">
            <p><%= @nominee.first_name%> <%= @nominee.last_name%></p>
          </h1>
        </div>
        <div class="ui  right dividing rail">
          <h4 class="header" style="text-decoration: underline;">Biography</h4>
          <h1>
            <%= @nominee.biography%>
          </h1>
          
        </div>
        <div class="ui card" >
          <div class="ui slide masked reveal">
            <%= image_tag("lolx.jfif", class: "visible content")%>
            <%= image_tag("lolx.jfif", class: "hidden content")%>
          </div>
        </div>
      </div> -->
    </div>
  </div> 
</div>

app/views/registry_citizens/index.html.erb
<div class="ui center aligned container" >
  <div class="ui huge yellow inverted segment" >
    <%= link_to "CREATE NEW BIRTH DEATH REGISTRY CITIZEN DATA", new_registry_citizen_path, class: "floating ui black tag label"%>
    <span class="ui huge header">BIRTH AND DEATH REGISTRY</span>
  </div>
  <div class="ui center aligned container" style="width: 50%">
    <%@registry_citizens.each do |citizen|%>
      <div class="ui segment">
        <div class="ui vertical divider"><i class="info icon"></i></div>
        <div class="ui two column grid">
          <%= link_to registry_citizen_path(citizen), class: "column" do %>
            <div class="ui small stretched image">
              <%= image_tag(citizen.image, class: "ui rounded image") %>
            </div>
          <% end %>
          <%= link_to electoral_citizen_path(citizen), class: "column" do %>
          <div class="column" style="color: black;">
            <h2 class="header"><%= "#{citizen.first_name.upcase} #{citizen.last_name.upcase}"%></h2>
            <h5 class="header" style="text-decoration: underline; font-weight:lighter">General ID</h5>
            <h3 class="header"><%= citizen.general_id%></h3>
            <h5 class="header" style="text-decoration: underline; font-weight:lighter">Description</h5>
            <h3 class="header"><%= citizen.description%></h3>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>