config/routes.rb
Rails.application.routes.draw do
  resources :nominees
  resources :awards
  resources :electoral_citizens
  resources :registry_citizens
  resources :nhis_citizens
  resources :dvla_citizens
  resources :all_citizens
  get 'static_pages/about'
  get 'all_citizens/info'
  devise_for :users
  root "all_citizens#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
  has_many :nominees, dependent: :destroy
  validates_presence_of :name, :description
end

app/models/dvla_citizen.rb
class DvlaCitizen < ApplicationRecord
  connects_to database: { writing: :DVLA, reading: :DVLA }
end

app/models/electoral_citizen.rb
class ElectoralCitizen < ApplicationRecord
end

app/models/nhis_citizen.rb
class NhisCitizen < ApplicationRecord
  connects_to database: { writing: :NHIS, reading: :NHIS }
end

app/models/nominee.rb
class Nominee < ApplicationRecord
  belongs_to :award

  validates_presence_of :first_name, :last_name, :biography
end

app/models/registry_citizen.rb
class RegistryCitizen < ApplicationRecord
  connects_to database: { writing: :Birthdeathregistry, reading: :Birthdeathregistry }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/all_citizens_controller.rb
class AllCitizensController < ApplicationController
  before_action :authenticate_user!

  def index
    @registry_citizens = RegistryCitizen.all
    @electoral_citizens = ElectoralCitizen.all
    @nhis_citizens = NhisCitizen.all
    @dvla_citizens = DvlaCitizen.all
  end

  def create
    key = all_citizen_params["key"].strip
    search = all_citizen_params["gender"]

    ActiveRecord::Base.connected_to(role: :reading) do
      # all code in this block will be connected to the reading role
    end

    if search == "1"
      @result = [RegistryCitizen, ElectoralCitizen, NhisCitizen, DvlaCitizen].map do |model|
        model.where('last_name LIKE ?', key)
      end
    elsif search == "2"
      @result = [RegistryCitizen, ElectoralCitizen, NhisCitizen, DvlaCitizen].map do |model|
        model.where('general_id LIKE ?', key.to_i)
      end
    else
      @result = [RegistryCitizen, ElectoralCitizen, NhisCitizen, DvlaCitizen].map do |model|
        model.where('first_name LIKE ?', key)
      end
    end

    session[:result] = @result

    # @registry_citizens = []
    # @electoral_citizens = []
    # @nhis_citizens = []
    # @dvla_citizens = []

    redirect_to all_citizens_info_path
  end

  def info; end

  def show; end

  private

  def all_citizen_params
    params.permit(:key, :gender, :authenticity_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  before_action :authenticate_user!
  def index
    @awards = Award.all
  end

  def new
    @award = Award.new
  end

  def show
    @award = Award.find_by(id: params[:id])
  end

  def create
    @award = Award.new(awards_params)

    if @award.save
      flash[:notice] = "Created an Award"
      redirect_to @award
    else
      render :new
    end
  end

  private
  def awards_params
    params.require(:award).permit(:name, :description, :image)
  end

end

app/controllers/dvla_citizens_controller.rb
class DvlaCitizensController < ApplicationController
  before_action :authenticate_user!
  def index
    @dvla_citizens = DvlaCitizen.all
  end

  def show
    @dvla_citizen = DvlaCitizen.find(params[:id])
  end

  def new
    @dvla_citizen = DvlaCitizen.new
    # @awards = Award.all
  end

  def create
    filename = "#{Time.now.to_i}#{File.extname(dvla_citizen_params[:image].tempfile)}"
    @dvla_citizen = DvlaCitizen.new(dvla_citizen_params.except(:image))
    @dvla_citizen.image = filename

    if @dvla_citizen.save
      flash[:notice] = 'DVLA Record Created!'
      file = dvla_citizen_params[:image].tempfile
      destination = "#{Rails.root}/app/assets/images/#{@dvla_citizen.image}"
      File.copy_stream(file, destination)
      redirect_to @dvla_citizen
    else
      render :new
    end
  end

  private

  def dvla_citizen_params
    params.require(:dvla_citizen).permit(:first_name, :last_name, :general_id, :description, :image)
  end
end

app/controllers/nhis_citizens_controller.rb
class NhisCitizensController < ApplicationController
  before_action :authenticate_user!
  def index
    @nhis_citizens = NhisCitizen.all
  end

  def show
    @nhis_citizen = NhisCitizen.find(params[:id])
  end

  def new
    @nhis_citizen = NhisCitizen.new
    # @awards = Award.all
  end

  def create
    filename = "#{Time.now.to_i}#{File.extname(nhis_citizen_params[:image].tempfile)}"
    @nhis_citizen = NhisCitizen.new(nhis_citizen_params.except(:image))
    @nhis_citizen.image = filename

    if @nhis_citizen.save
      flash[:notice] = 'NHIS Record Created!'
      file = nhis_citizen_params[:image].tempfile
      destination = "#{Rails.root}/app/assets/images/#{@nhis_citizen.image}"
      File.copy_stream(file, destination)
      redirect_to @nhis_citizen
    else
      render :new
    end
  end

  private

  def nhis_citizen_params
    params.require(:nhis_citizen).permit(:first_name, :last_name, :general_id, :description, :image)
  end
end

app/controllers/nominees_controller.rb
class NomineesController < ApplicationController
  before_action :authenticate_user!
  def index
    @nominees =Nominee.all
  end

  def show
    @nominee = Nominee.find(params[:id])
  end

  def new
    @nominee = Nominee.new
    @awards = Award.all
  end

  def create
    @nominee = Nominee.new(nominees_params)
    @nominee.award_id = params[:award]

    if @nominee.save
      flash[:notice] = "Created an Award"
      redirect_to @nominee
    else
      render :new
    end
  end

  private
  def nominees_params
    params.require(:nominee).permit(:first_name, :last_name, :biography, :video, :image)
  end
end

app/controllers/registry_citizens_controller.rb
class RegistryCitizensController < ApplicationController
  before_action :authenticate_user!
  def index
    @registry_citizens =RegistryCitizen.all
  end

  def show
    @registry_citizen = RegistryCitizen.find(params[:id])
  end

  def new
    @registry_citizen = RegistryCitizen.new
    # @awards = Award.all
  end

  def create
    filename = "#{Time.now.to_i}#{File.extname(registry_citizen_params[:image].tempfile)}"
    @registry_citizen = RegistryCitizen.new(registry_citizen_params.except(:image))
    @registry_citizen.image = filename

    if @registry_citizen.save
      flash[:notice] = 'Birth And Death Registry Record Created!'
      file = registry_citizen_params[:image].tempfile
      destination = "#{Rails.root}/app/assets/images/#{@registry_citizen.image}"
      File.copy_stream(file, destination)
      redirect_to @registry_citizen
    else
      render :new
    end
  end

  private
  def registry_citizen_params
    params.require(:registry_citizen).permit(:first_name, :last_name, :general_id, :description, :image)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/nominees_helper.rb
module NomineesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_errors.html.erb
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<div class="ui vertical footer segment">
<div class="ui center aligned container">
  <i class="big facebook icon"></i>
  <i class="big instagram icon"></i>
  <i class="big twitter icon"></i>
  <i class="big youtube icon"></i>
</div>
</div>

app/views/layouts/_javascript.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
<script>
  $(document).ready(function() {
    $(".ui.toggle.button").click(function() {
      let menu = $(this)
        .parent()
        .parent()
        .parent();
      $(".ui.vertical.menu", menu).toggle(100);
    });

    $(".ui.dropdown").dropdown();

    $(".ui.progress").progress({
      showActivity: false
    });
  });
</script>

app/views/layouts/_navbar.html.erb
<div class="ui tablet computer only padded grid">
  <div class="ui top fixed  large borderless menu">
    <div class="ui container">
      <a href="<%= all_citizens_path %>" style="display:flex; justify-content:center; align-items:center">
        <i class="big folder outline icon"></i>
      </a>
      <% if current_user %>
        <%= link_to "EC", electoral_citizens_path, class: "item"%>
        <%= link_to "B&D REG", registry_citizens_path, class: "item" %>
        <%= link_to "NHIS", nhis_citizens_path, class: "item" %>
        <%= link_to "DVLA", dvla_citizens_path, class: "item" %>
      <% end %>
      <%= link_to "About", static_pages_about_path, class: "item" %>

    <div class="right menu">
      <% if current_user %>
        <%= link_to "Logout", destroy_user_session_path, class: "ui item"%>
      <%else%>

      <%- if controller_name != 'sessions' %>
        <div class="ui item">
          <%= link_to "Login", new_user_session_path, class: "ui inverted blue button"%>
        </div>
      <% end %>

      <%- if controller_name != 'registrations' %>
        <div class="ui item">
          <%= link_to "SignUp", new_user_registration_path, class: "ui pink inverted button"%>
        </div>
      <% end %>
        
      <% end %>
      
    </div>
</div>

  </div>
</div>

<div class="ui mobile only grid">
  <div class="ui inverted top fixed borderless menu">
    <%= link_to "Awards", awards_path, class: "header item"%>
    <div class="right menu">
      <div class="item">
        <button class="ui icon toggle basic inverted button">
          <i class="content icon"></i>
        </button>
      </div>
    </div>
    <div class="ui inverted vertical borderless fluid menu">
      <%= link_to "Home", awards_path, class: "item"%>
      <%= link_to "Nominees", nominees_path, class: "item" %>
      <%= link_to "About", static_pages_about_path, class: "item" %>
      <% if current_user %>
        <%= link_to "Logout", destroy_user_session_path, class: "ui item"%>
      <%else%>
        <div class="ui item">
          <%= link_to "Login", new_user_session_path, class: "ui inverted blue primary button"%>
        </div>
        <div class="ui item">
          <%= link_to "SignUp", new_user_registration_path, class: "ui pink inverted button"%>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=no"
    />
    <meta
      name="description"
      content="Semantic-UI-Forest, collection of design, themes and templates for Semantic-UI."
    />
    <meta name="keywords" content="Semantic-UI, Theme, Design, Template" />
    <title>Theme Template for Semantic-UI</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render partial: 'layouts/navbar'%>
    <%= render partial: 'layouts/errors'%>
    
    <div id="content">
      <%= yield %>
    </div>
    
  </body>

  <%= render 'layouts/footer' %>
  <%= render 'layouts/javascript' %>
  
</html>